name: CI
on:
- pull_request
  
jobs:
  yamllint:
    name: yaml lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: "./resources/translations"
        yamllint_strict: false # Seems to correlate to the return code.
        yamllint_comment: true # View them in the "Files changed" tab.
        yamllint_config_datapath: '{"rules":{"new-lines":"disable","document-start":"disable","trailing-spaces":{"level":"warning"}}}'
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
